# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork"
#
# Default user: admin
# Default password: admin

volumes:
  geonetwork:
  esdata:
  pgdata:
  pglog:

services:
  geonetwork:
    image: geonetwork:4.4
    healthcheck:
      test: curl http://localhost:8080/
      interval: 5s
      timeout: 5s
      retries: 30
    restart: always
    volumes:
      - geonetwork:/catalogue-data
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      WEBAPP_CONTEXT_PATH: /geonetwork
      DATA_DIR: /catalogue-data
      TZ: Europe/Amsterdam

      JAVA_OPTS: >-
        --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Djetty.httpConfig.requestHeaderSize=32768
        -Dorg.eclipse.jetty.server.Request.maxFormContentSize=500000
        -Dorg.eclipse.jetty.server.Request.maxFormKeys=4000
      # For remote debug
      # -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005

      GN_CONFIG_PROPERTIES: >-
        -Dgeonetwork.dir=/catalogue-data
        -Dgeonetwork.formatter.dir=/catalogue-data/data/formatter
        -Dgeonetwork.schema.dir=/opt/geonetwork/WEB-INF/data/config/schema_plugins
        -Dgeonetwork.indexConfig.dir=/opt/geonetwork/WEB-INF/data/config/index
        -Dgeonetwork.schemapublication.dir=/opt/geonetwork/WEB-INF/data/resources/schemapublication
        -Dgeonetwork.htmlcache.dir=/opt/geonetwork/WEB-INF/data/resources/htmlcache
        -Des.host=${ES_HOST}
        -Des.protocol=${ES_PROTOCOL}
        -Des.port=${ES_PORT}
        -Des.url=${ES_URL}
        -Des.username=
        -Des.password=
        -Dgeonetwork.ESFeaturesProxy.targetUri=http://elasticsearch:9200/gn-features/{_}
        -Dgeonetwork.HttpDashboardProxy.targetUri=${KIBANA_URL}
        -Dkb.url=${KIBANA_URL}

      GEONETWORK_DB_TYPE: ${GEONETWORK_DB_TYPE}
      GEONETWORK_DB_HOST: ${GEONETWORK_DB_HOST}
      GEONETWORK_DB_PORT: ${GEONETWORK_DB_PORT}
      GEONETWORK_DB_NAME: ${GEONETWORK_DB_NAME}
      GEONETWORK_DB_USERNAME: ${GEONETWORK_DB_USERNAME}
      GEONETWORK_DB_PASSWORD: ${GEONETWORK_DB_PASSWORD}

  database:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: [postgres, -c, log_statement=all, -c, logging_collector=true, -c, log_file_mode=0644, -c, log_directory=/var/log/postgresql, -c, log_filename=postgresql.log]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql

  elasticsearch:
    image: elasticsearch:7.17.15
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 2m
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      discovery.type: ${DISCOVERY_TYPE}
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.15
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      SERVER_BASEPATH: ${SERVER_BASEPATH}
      SERVER_REWRITEBASEPATH: ${SERVER_REWRITEBASEPATH}
      KIBANA_INDEX: ${KIBANA_INDEX}
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: ${XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED}
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: geonetwork-nginx:latest
    restart: always
    ports:
      - 80:80
      - ${NGINX_SSLPORT}:${NGINX_SSLPORT}
    depends_on:
      geonetwork:
        condition: service_healthy
    environment:
      - NGINX_SSLPORT=${NGINX_SSLPORT}
    volumes:
      - ./nginx/setup/geonetwork-docker_local.crt:/etc/nginx/certs/geonetwork-docker_local.crt:ro
      - ./nginx/setup/geonetwork-docker_local.key:/etc/nginx/certs/geonetwork-docker_local.key:ro
      - ./nginx/setup/html:/usr/share/nginx/html:ro
